const createNextIntlPlugin = require('next-intl/plugin');
 
const withNextIntl = createNextIntlPlugin();

/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    serverActions: true,
  },
  env: {
    GITHUB_ID: process.env.GITHUB_ID,
    GITHUB_SECRET: process.env.GITHUB_SECRET,
    GOOGLE_ID: process.env.GOOGLE_ID,
    GOOGLE_SECRET: process.env.GOOGLE_SECRET,
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    NEXT_PUBLIC_BASE_HOST: process.env.NEXT_PUBLIC_BASE_HOST,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,

    API_LOGIN: process.env.API_LOGIN,
    API_USERS: process.env.API_USERS,
    API_USER_STORE: process.env.API_USER_STORE,
    API_USER_UPDATE: process.env.API_USER_UPDATE,
    API_USER_PROFILE_UPDATE: process.env.API_USER_PROFILE_UPDATE,
    API_USER_PERMISSIONS: process.env.API_USER_PERMISSIONS,
    API_USER_PERMISSION_STORE: process.env.API_USER_PERMISSION_STORE,
    API_USER_PERMISSION_UPDATE: process.env.API_USER_PERMISSION_UPDATE,
    API_USER_ROLES: process.env.API_USER_ROLES,
    API_USER_ROLE_STORE: process.env.API_USER_ROLE_STORE,
    API_USER_ROLE_UPDATE: process.env.API_USER_ROLE_UPDATE,
    API_USER_APPROVAL_STORE: process.env.API_USER_APPROVAL_STORE,
    API_CONTACTS: process.env.API_CONTACTS,
    API_CONTACT_STORE: process.env.API_CONTACT_STORE,
    API_CONTACT_UPDATE: process.env.API_CONTACT_UPDATE,
    API_USER_STAFFS: process.env.API_USER_STAFFS,
    API_USER_STAFF_STORE: process.env.API_USER_STAFF_STORE,
    API_USER_STAFF_UPDATE: process.env.API_USER_STAFF_UPDATE,

    API_ACCOUNTING_ACCOUNTS: process.env.API_ACCOUNTING_ACCOUNTS,
    API_ACCOUNTING_ACCOUNT_STORE: process.env.API_ACCOUNTING_ACCOUNT_STORE,
    API_ACCOUNTING_ACCOUNT_UPDATE: process.env.API_ACCOUNTING_ACCOUNT_UPDATE,    
    API_ACCOUNTING_LEDGERS: process.env.API_ACCOUNTING_LEDGERS,
    API_ACCOUNTING_LEDGER_STORE: process.env.API_ACCOUNTING_LEDGER_STORE,
    API_ACCOUNTING_LEDGER_UPDATE: process.env.API_ACCOUNTING_LEDGER_UPDATE,
    API_ACCOUNTING_LEDGER_SHOW: process.env.API_ACCOUNTING_LEDGER_SHOW,
    API_ACCOUNTING_LEDGER_PATCH: process.env.API_ACCOUNTING_LEDGER_PATCH,
    API_ACCOUNTING_BALANCE: process.env.API_ACCOUNTING_BALANCE,
    API_ACCOUNTING_LEDGERS_MUTATION: process.env.API_ACCOUNTING_LEDGERS_MUTATION,
    API_ACCOUNTING_BALANCE_SHEET: process.env.API_ACCOUNTING_BALANCE_SHEET,
    API_ACCOUNTING_ACCOUNTS_GROUP: process.env.API_ACCOUNTING_ACCOUNTS_GROUP,
    API_ACCOUNTING_ACCOUNTS_MODULE: process.env.API_ACCOUNTING_ACCOUNTS_MODULE,

    API_CAPITAL_USERS: process.env.API_CAPITAL_USERS,
    API_CAPITAL_USER_STORE: process.env.API_CAPITAL_USER_STORE,
    API_CAPITAL_USER_UPDATE: process.env.API_CAPITAL_USER_UPDATE,
    API_CAPITAL_USER_UPDATE_PROFILE: process.env.API_CAPITAL_USER_UPDATE_PROFILE,
    API_CAPITAL_REQUESTS: process.env.API_CAPITAL_REQUESTS,
    API_CAPITAL_USER_REGISTERED: process.env.API_CAPITAL_USER_REGISTERED,
    API_CAPITAL_REQUESTS_PATCH: process.env.API_CAPITAL_REQUESTS_PATCH,    
    API_CAPITAL_STORE: process.env.API_CAPITAL_STORE,
    API_CAPITAL_USER_ACTIVATE: process.env.API_CAPITAL_USER_ACTIVATE,
    API_CAPITAL: process.env.API_CAPITAL,
    API_CAPITAL_USER_ACTIVATED: process.env.API_CAPITAL_USER_ACTIVATED,

    API_PRODUCTS: process.env.API_PRODUCTS,
    API_PRODUCTS_STORE: process.env.API_PRODUCTS_STORE,
    API_PRODUCTS_UPDATE: process.env.API_PRODUCTS_UPDATE,
    API_PRODUCTS_DELETE: process.env.API_PRODUCTS_DELETE,
    API_PRODUCTS_GET_UNIT: process.env.API_PRODUCTS_GET_UNIT,
    API_PRODUCTS_GET_WAREHOUSE: process.env.API_PRODUCTS_GET_WAREHOUSE,
    API_PRODUCTS_GET_CODE: process.env.API_PRODUCTS_GET_CODE,

    API_SUPPLIERS: process.env.API_SUPPLIERS,
    API_SUPPLIERS_STORE: process.env.API_SUPPLIERS_STORE,
    API_SUPPLIERS_UPDATE: process.env.API_SUPPLIERS_UPDATE,
    API_SUPPLIERS_DELETE: process.env.API_SUPPLIERS_DELETE,

    API_WAREHOUSES: process.env.API_WAREHOUSES,
    API_WAREHOUSES_STORE: process.env.API_WAREHOUSES_STORE,
    API_WAREHOUSES_UPDATE: process.env.API_WAREHOUSES_UPDATE,
    API_WAREHOUSES_DELETE: process.env.API_WAREHOUSES_DELETE,

    API_TRANSACTIONS: process.env.API_TRANSACTIONS,
    API_TRANSACTIONS_STORE: process.env.API_TRANSACTIONS_STORE,
    API_TRANSACTIONS_SHOW: process.env.API_TRANSACTIONS_SHOW,
    API_TRANSACTIONS_UPDATE: process.env.API_TRANSACTIONS_UPDATE,
    API_TRANSACTIONS_DELETE: process.env.API_TRANSACTIONS_DELETE,
    API_TRANSACTIONS_PRODUCTION: process.env.API_TRANSACTIONS_PRODUCTION,
    API_TRANSACTIONS_PRODUCTION_UPDATE: process.env.API_TRANSACTIONS_PRODUCTION_UPDATE,
    API_TRANSACTIONS_GET_PRODUCT: process.env.API_TRANSACTIONS_GET_PRODUCT,
    API_TRANSACTIONS_GET_PRODUCT_PRODUCTION: process.env.API_TRANSACTIONS_GET_PRODUCT_PRODUCTION,
    API_TRANSACTIONS_GET_SUPPLIER: process.env.API_TRANSACTIONS_GET_SUPPLIER,
    API_TRANSACTIONS_GET_CUSTOMER: process.env.API_TRANSACTIONS_GET_CUSTOMER,
    API_TRANSACTIONS_GET_WAREHOUSE: process.env.API_TRANSACTIONS_GET_WAREHOUSE,
    API_TRANSACTIONS_CONTINUE: process.env.API_TRANSACTIONS_CONTINUE,
    
    API_UNITS_DETAIL_STORE: process.env.API_UNITS_DETAIL_STORE,
    API_UNITS: process.env.API_UNITS,
    API_UNITS_UPDATE: process.env.API_UNITS_UPDATE,
    API_UNITS_STORE: process.env.API_UNITS_STORE,

    API_PAYRECEIVABLES: process.env.API_PAYRECEIVABLES,
    API_PAYRECEIVABLES_STORE: process.env.API_PAYRECEIVABLES_STORE,
    API_PAYRECEIVABLES_UPDATE: process.env.API_PAYRECEIVABLES_UPDATE,
    API_PAYRECEIVABLES_DELETE: process.env.API_PAYRECEIVABLES_DELETE,
    API_PAYRECEIVABLES_SHOW: process.env.API_PAYRECEIVABLES_SHOW,
    API_PAYRECEIVABLES_TRANSACTION: process.env.API_PAYRECEIVABLES_TRANSACTION,
    API_PAYRECEIVABLES_TRANSACTION_STORE: process.env.API_PAYRECEIVABLES_TRANSACTION_STORE,
    API_PAYRECEIVABLES_TRANSACTION_UPDATE: process.env.API_PAYRECEIVABLES_TRANSACTION_UPDATE,
    API_PAYRECEIVABLES_TRANSACTION_DELETE: process.env.API_PAYRECEIVABLES_TRANSACTION_DELETE
  }
}

module.exports = withNextIntl(nextConfig)
